/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectRouteImport } from './routes/project'
import { Route as NotaryRouteImport } from './routes/notary'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvestorRouteImport } from './routes/investor'
import { Route as DeveloperRouteImport } from './routes/developer'
import { Route as CertifierRouteImport } from './routes/certifier'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotaryIndexRouteImport } from './routes/notary.index'
import { Route as DeveloperIndexRouteImport } from './routes/developer.index'
import { Route as CertifierIndexRouteImport } from './routes/certifier.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as NotarySignedRouteImport } from './routes/notary.signed'
import { Route as NotaryProfileRouteImport } from './routes/notary.profile'
import { Route as NotaryDossiersRouteImport } from './routes/notary.dossiers'
import { Route as InvestorUnitsRouteImport } from './routes/investor.units'
import { Route as InvestorProfileRouteImport } from './routes/investor.profile'
import { Route as InvestorNotificationsRouteImport } from './routes/investor.notifications'
import { Route as InvestorMenuRouteImport } from './routes/investor.menu'
import { Route as InvestorFavoritesRouteImport } from './routes/investor.favorites'
import { Route as InvestorBuyRouteImport } from './routes/investor.buy'
import { Route as DeveloperUnitsRouteImport } from './routes/developer.units'
import { Route as DeveloperProjectsRouteImport } from './routes/developer.projects'
import { Route as DeveloperProgressRouteImport } from './routes/developer.progress'
import { Route as DeveloperProfileRouteImport } from './routes/developer.profile'
import { Route as DeveloperInvestorsRouteImport } from './routes/developer.investors'
import { Route as DeveloperDocumentationRouteImport } from './routes/developer.documentation'
import { Route as DeveloperCapitalRouteImport } from './routes/developer.capital'
import { Route as DeveloperAuditLogRouteImport } from './routes/developer.audit-log'
import { Route as CertifierProfileRouteImport } from './routes/certifier.profile'
import { Route as CertifierIssuedRouteImport } from './routes/certifier.issued'
import { Route as CertifierAssignedRouteImport } from './routes/certifier.assigned'
import { Route as ProjectProjectIdIndexRouteImport } from './routes/project.$projectId.index'
import { Route as PublicDossierShareTokenRouteImport } from './routes/public.dossier.$shareToken'
import { Route as ProjectProjectIdProgressRouteImport } from './routes/project.$projectId.progress'
import { Route as ProjectProjectIdDeveloperRouteImport } from './routes/project.$projectId.developer'
import { Route as NotaryDossierDossierIdRouteImport } from './routes/notary.dossier.$dossierId'
import { Route as DeveloperProjectNewRouteImport } from './routes/developer.project.new'
import { Route as CertifierStageStageIdRouteImport } from './routes/certifier.stage.$stageId'
import { Route as InvestorUnitUnitIdIndexRouteImport } from './routes/investor.unit.$unitId.index'
import { Route as DeveloperProjectProjectIdIndexRouteImport } from './routes/developer.project.$projectId.index'
import { Route as ProjectProjectIdStageStageIdRouteImport } from './routes/project.$projectId.stage.$stageId'
import { Route as InvestorUnitUnitIdNotificationsRouteImport } from './routes/investor.unit.$unitId.notifications'
import { Route as InvestorUnitUnitIdDossierRouteImport } from './routes/investor.unit.$unitId.dossier'
import { Route as InvestorUnitUnitIdContractRouteImport } from './routes/investor.unit.$unitId.contract'
import { Route as DeveloperProjectProjectIdUploadRouteImport } from './routes/developer.project.$projectId.upload'
import { Route as DeveloperProjectProjectIdUnitsRouteImport } from './routes/developer.project.$projectId.units'
import { Route as DeveloperProjectProjectIdInviteRouteImport } from './routes/developer.project.$projectId.invite'
import { Route as DeveloperProjectProjectIdContractsRouteImport } from './routes/developer.project.$projectId.contracts'

const ProjectRoute = ProjectRouteImport.update({
  id: '/project',
  path: '/project',
  getParentRoute: () => rootRouteImport,
} as any)
const NotaryRoute = NotaryRouteImport.update({
  id: '/notary',
  path: '/notary',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestorRoute = InvestorRouteImport.update({
  id: '/investor',
  path: '/investor',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperRoute = DeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => rootRouteImport,
} as any)
const CertifierRoute = CertifierRouteImport.update({
  id: '/certifier',
  path: '/certifier',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotaryIndexRoute = NotaryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NotaryRoute,
} as any)
const DeveloperIndexRoute = DeveloperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeveloperRoute,
} as any)
const CertifierIndexRoute = CertifierIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CertifierRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const NotarySignedRoute = NotarySignedRouteImport.update({
  id: '/signed',
  path: '/signed',
  getParentRoute: () => NotaryRoute,
} as any)
const NotaryProfileRoute = NotaryProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => NotaryRoute,
} as any)
const NotaryDossiersRoute = NotaryDossiersRouteImport.update({
  id: '/dossiers',
  path: '/dossiers',
  getParentRoute: () => NotaryRoute,
} as any)
const InvestorUnitsRoute = InvestorUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => InvestorRoute,
} as any)
const InvestorProfileRoute = InvestorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => InvestorRoute,
} as any)
const InvestorNotificationsRoute = InvestorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => InvestorRoute,
} as any)
const InvestorMenuRoute = InvestorMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => InvestorRoute,
} as any)
const InvestorFavoritesRoute = InvestorFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => InvestorRoute,
} as any)
const InvestorBuyRoute = InvestorBuyRouteImport.update({
  id: '/buy',
  path: '/buy',
  getParentRoute: () => InvestorRoute,
} as any)
const DeveloperUnitsRoute = DeveloperUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperProjectsRoute = DeveloperProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperProgressRoute = DeveloperProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperProfileRoute = DeveloperProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperInvestorsRoute = DeveloperInvestorsRouteImport.update({
  id: '/investors',
  path: '/investors',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperDocumentationRoute = DeveloperDocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperCapitalRoute = DeveloperCapitalRouteImport.update({
  id: '/capital',
  path: '/capital',
  getParentRoute: () => DeveloperRoute,
} as any)
const DeveloperAuditLogRoute = DeveloperAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => DeveloperRoute,
} as any)
const CertifierProfileRoute = CertifierProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CertifierRoute,
} as any)
const CertifierIssuedRoute = CertifierIssuedRouteImport.update({
  id: '/issued',
  path: '/issued',
  getParentRoute: () => CertifierRoute,
} as any)
const CertifierAssignedRoute = CertifierAssignedRouteImport.update({
  id: '/assigned',
  path: '/assigned',
  getParentRoute: () => CertifierRoute,
} as any)
const ProjectProjectIdIndexRoute = ProjectProjectIdIndexRouteImport.update({
  id: '/$projectId/',
  path: '/$projectId/',
  getParentRoute: () => ProjectRoute,
} as any)
const PublicDossierShareTokenRoute = PublicDossierShareTokenRouteImport.update({
  id: '/public/dossier/$shareToken',
  path: '/public/dossier/$shareToken',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectProjectIdProgressRoute =
  ProjectProjectIdProgressRouteImport.update({
    id: '/$projectId/progress',
    path: '/$projectId/progress',
    getParentRoute: () => ProjectRoute,
  } as any)
const ProjectProjectIdDeveloperRoute =
  ProjectProjectIdDeveloperRouteImport.update({
    id: '/$projectId/developer',
    path: '/$projectId/developer',
    getParentRoute: () => ProjectRoute,
  } as any)
const NotaryDossierDossierIdRoute = NotaryDossierDossierIdRouteImport.update({
  id: '/dossier/$dossierId',
  path: '/dossier/$dossierId',
  getParentRoute: () => NotaryRoute,
} as any)
const DeveloperProjectNewRoute = DeveloperProjectNewRouteImport.update({
  id: '/project/new',
  path: '/project/new',
  getParentRoute: () => DeveloperRoute,
} as any)
const CertifierStageStageIdRoute = CertifierStageStageIdRouteImport.update({
  id: '/stage/$stageId',
  path: '/stage/$stageId',
  getParentRoute: () => CertifierRoute,
} as any)
const InvestorUnitUnitIdIndexRoute = InvestorUnitUnitIdIndexRouteImport.update({
  id: '/unit/$unitId/',
  path: '/unit/$unitId/',
  getParentRoute: () => InvestorRoute,
} as any)
const DeveloperProjectProjectIdIndexRoute =
  DeveloperProjectProjectIdIndexRouteImport.update({
    id: '/project/$projectId/',
    path: '/project/$projectId/',
    getParentRoute: () => DeveloperRoute,
  } as any)
const ProjectProjectIdStageStageIdRoute =
  ProjectProjectIdStageStageIdRouteImport.update({
    id: '/$projectId/stage/$stageId',
    path: '/$projectId/stage/$stageId',
    getParentRoute: () => ProjectRoute,
  } as any)
const InvestorUnitUnitIdNotificationsRoute =
  InvestorUnitUnitIdNotificationsRouteImport.update({
    id: '/unit/$unitId/notifications',
    path: '/unit/$unitId/notifications',
    getParentRoute: () => InvestorRoute,
  } as any)
const InvestorUnitUnitIdDossierRoute =
  InvestorUnitUnitIdDossierRouteImport.update({
    id: '/unit/$unitId/dossier',
    path: '/unit/$unitId/dossier',
    getParentRoute: () => InvestorRoute,
  } as any)
const InvestorUnitUnitIdContractRoute =
  InvestorUnitUnitIdContractRouteImport.update({
    id: '/unit/$unitId/contract',
    path: '/unit/$unitId/contract',
    getParentRoute: () => InvestorRoute,
  } as any)
const DeveloperProjectProjectIdUploadRoute =
  DeveloperProjectProjectIdUploadRouteImport.update({
    id: '/project/$projectId/upload',
    path: '/project/$projectId/upload',
    getParentRoute: () => DeveloperRoute,
  } as any)
const DeveloperProjectProjectIdUnitsRoute =
  DeveloperProjectProjectIdUnitsRouteImport.update({
    id: '/project/$projectId/units',
    path: '/project/$projectId/units',
    getParentRoute: () => DeveloperRoute,
  } as any)
const DeveloperProjectProjectIdInviteRoute =
  DeveloperProjectProjectIdInviteRouteImport.update({
    id: '/project/$projectId/invite',
    path: '/project/$projectId/invite',
    getParentRoute: () => DeveloperRoute,
  } as any)
const DeveloperProjectProjectIdContractsRoute =
  DeveloperProjectProjectIdContractsRouteImport.update({
    id: '/project/$projectId/contracts',
    path: '/project/$projectId/contracts',
    getParentRoute: () => DeveloperRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/certifier': typeof CertifierRouteWithChildren
  '/developer': typeof DeveloperRouteWithChildren
  '/investor': typeof InvestorRouteWithChildren
  '/login': typeof LoginRoute
  '/notary': typeof NotaryRouteWithChildren
  '/project': typeof ProjectRouteWithChildren
  '/certifier/assigned': typeof CertifierAssignedRoute
  '/certifier/issued': typeof CertifierIssuedRoute
  '/certifier/profile': typeof CertifierProfileRoute
  '/developer/audit-log': typeof DeveloperAuditLogRoute
  '/developer/capital': typeof DeveloperCapitalRoute
  '/developer/documentation': typeof DeveloperDocumentationRoute
  '/developer/investors': typeof DeveloperInvestorsRoute
  '/developer/profile': typeof DeveloperProfileRoute
  '/developer/progress': typeof DeveloperProgressRoute
  '/developer/projects': typeof DeveloperProjectsRoute
  '/developer/units': typeof DeveloperUnitsRoute
  '/investor/buy': typeof InvestorBuyRoute
  '/investor/favorites': typeof InvestorFavoritesRoute
  '/investor/menu': typeof InvestorMenuRoute
  '/investor/notifications': typeof InvestorNotificationsRoute
  '/investor/profile': typeof InvestorProfileRoute
  '/investor/units': typeof InvestorUnitsRoute
  '/notary/dossiers': typeof NotaryDossiersRoute
  '/notary/profile': typeof NotaryProfileRoute
  '/notary/signed': typeof NotarySignedRoute
  '/admin/': typeof AdminIndexRoute
  '/certifier/': typeof CertifierIndexRoute
  '/developer/': typeof DeveloperIndexRoute
  '/notary/': typeof NotaryIndexRoute
  '/certifier/stage/$stageId': typeof CertifierStageStageIdRoute
  '/developer/project/new': typeof DeveloperProjectNewRoute
  '/notary/dossier/$dossierId': typeof NotaryDossierDossierIdRoute
  '/project/$projectId/developer': typeof ProjectProjectIdDeveloperRoute
  '/project/$projectId/progress': typeof ProjectProjectIdProgressRoute
  '/public/dossier/$shareToken': typeof PublicDossierShareTokenRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/developer/project/$projectId/contracts': typeof DeveloperProjectProjectIdContractsRoute
  '/developer/project/$projectId/invite': typeof DeveloperProjectProjectIdInviteRoute
  '/developer/project/$projectId/units': typeof DeveloperProjectProjectIdUnitsRoute
  '/developer/project/$projectId/upload': typeof DeveloperProjectProjectIdUploadRoute
  '/investor/unit/$unitId/contract': typeof InvestorUnitUnitIdContractRoute
  '/investor/unit/$unitId/dossier': typeof InvestorUnitUnitIdDossierRoute
  '/investor/unit/$unitId/notifications': typeof InvestorUnitUnitIdNotificationsRoute
  '/project/$projectId/stage/$stageId': typeof ProjectProjectIdStageStageIdRoute
  '/developer/project/$projectId/': typeof DeveloperProjectProjectIdIndexRoute
  '/investor/unit/$unitId/': typeof InvestorUnitUnitIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/investor': typeof InvestorRouteWithChildren
  '/login': typeof LoginRoute
  '/project': typeof ProjectRouteWithChildren
  '/certifier/assigned': typeof CertifierAssignedRoute
  '/certifier/issued': typeof CertifierIssuedRoute
  '/certifier/profile': typeof CertifierProfileRoute
  '/developer/audit-log': typeof DeveloperAuditLogRoute
  '/developer/capital': typeof DeveloperCapitalRoute
  '/developer/documentation': typeof DeveloperDocumentationRoute
  '/developer/investors': typeof DeveloperInvestorsRoute
  '/developer/profile': typeof DeveloperProfileRoute
  '/developer/progress': typeof DeveloperProgressRoute
  '/developer/projects': typeof DeveloperProjectsRoute
  '/developer/units': typeof DeveloperUnitsRoute
  '/investor/buy': typeof InvestorBuyRoute
  '/investor/favorites': typeof InvestorFavoritesRoute
  '/investor/menu': typeof InvestorMenuRoute
  '/investor/notifications': typeof InvestorNotificationsRoute
  '/investor/profile': typeof InvestorProfileRoute
  '/investor/units': typeof InvestorUnitsRoute
  '/notary/dossiers': typeof NotaryDossiersRoute
  '/notary/profile': typeof NotaryProfileRoute
  '/notary/signed': typeof NotarySignedRoute
  '/admin': typeof AdminIndexRoute
  '/certifier': typeof CertifierIndexRoute
  '/developer': typeof DeveloperIndexRoute
  '/notary': typeof NotaryIndexRoute
  '/certifier/stage/$stageId': typeof CertifierStageStageIdRoute
  '/developer/project/new': typeof DeveloperProjectNewRoute
  '/notary/dossier/$dossierId': typeof NotaryDossierDossierIdRoute
  '/project/$projectId/developer': typeof ProjectProjectIdDeveloperRoute
  '/project/$projectId/progress': typeof ProjectProjectIdProgressRoute
  '/public/dossier/$shareToken': typeof PublicDossierShareTokenRoute
  '/project/$projectId': typeof ProjectProjectIdIndexRoute
  '/developer/project/$projectId/contracts': typeof DeveloperProjectProjectIdContractsRoute
  '/developer/project/$projectId/invite': typeof DeveloperProjectProjectIdInviteRoute
  '/developer/project/$projectId/units': typeof DeveloperProjectProjectIdUnitsRoute
  '/developer/project/$projectId/upload': typeof DeveloperProjectProjectIdUploadRoute
  '/investor/unit/$unitId/contract': typeof InvestorUnitUnitIdContractRoute
  '/investor/unit/$unitId/dossier': typeof InvestorUnitUnitIdDossierRoute
  '/investor/unit/$unitId/notifications': typeof InvestorUnitUnitIdNotificationsRoute
  '/project/$projectId/stage/$stageId': typeof ProjectProjectIdStageStageIdRoute
  '/developer/project/$projectId': typeof DeveloperProjectProjectIdIndexRoute
  '/investor/unit/$unitId': typeof InvestorUnitUnitIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/certifier': typeof CertifierRouteWithChildren
  '/developer': typeof DeveloperRouteWithChildren
  '/investor': typeof InvestorRouteWithChildren
  '/login': typeof LoginRoute
  '/notary': typeof NotaryRouteWithChildren
  '/project': typeof ProjectRouteWithChildren
  '/certifier/assigned': typeof CertifierAssignedRoute
  '/certifier/issued': typeof CertifierIssuedRoute
  '/certifier/profile': typeof CertifierProfileRoute
  '/developer/audit-log': typeof DeveloperAuditLogRoute
  '/developer/capital': typeof DeveloperCapitalRoute
  '/developer/documentation': typeof DeveloperDocumentationRoute
  '/developer/investors': typeof DeveloperInvestorsRoute
  '/developer/profile': typeof DeveloperProfileRoute
  '/developer/progress': typeof DeveloperProgressRoute
  '/developer/projects': typeof DeveloperProjectsRoute
  '/developer/units': typeof DeveloperUnitsRoute
  '/investor/buy': typeof InvestorBuyRoute
  '/investor/favorites': typeof InvestorFavoritesRoute
  '/investor/menu': typeof InvestorMenuRoute
  '/investor/notifications': typeof InvestorNotificationsRoute
  '/investor/profile': typeof InvestorProfileRoute
  '/investor/units': typeof InvestorUnitsRoute
  '/notary/dossiers': typeof NotaryDossiersRoute
  '/notary/profile': typeof NotaryProfileRoute
  '/notary/signed': typeof NotarySignedRoute
  '/admin/': typeof AdminIndexRoute
  '/certifier/': typeof CertifierIndexRoute
  '/developer/': typeof DeveloperIndexRoute
  '/notary/': typeof NotaryIndexRoute
  '/certifier/stage/$stageId': typeof CertifierStageStageIdRoute
  '/developer/project/new': typeof DeveloperProjectNewRoute
  '/notary/dossier/$dossierId': typeof NotaryDossierDossierIdRoute
  '/project/$projectId/developer': typeof ProjectProjectIdDeveloperRoute
  '/project/$projectId/progress': typeof ProjectProjectIdProgressRoute
  '/public/dossier/$shareToken': typeof PublicDossierShareTokenRoute
  '/project/$projectId/': typeof ProjectProjectIdIndexRoute
  '/developer/project/$projectId/contracts': typeof DeveloperProjectProjectIdContractsRoute
  '/developer/project/$projectId/invite': typeof DeveloperProjectProjectIdInviteRoute
  '/developer/project/$projectId/units': typeof DeveloperProjectProjectIdUnitsRoute
  '/developer/project/$projectId/upload': typeof DeveloperProjectProjectIdUploadRoute
  '/investor/unit/$unitId/contract': typeof InvestorUnitUnitIdContractRoute
  '/investor/unit/$unitId/dossier': typeof InvestorUnitUnitIdDossierRoute
  '/investor/unit/$unitId/notifications': typeof InvestorUnitUnitIdNotificationsRoute
  '/project/$projectId/stage/$stageId': typeof ProjectProjectIdStageStageIdRoute
  '/developer/project/$projectId/': typeof DeveloperProjectProjectIdIndexRoute
  '/investor/unit/$unitId/': typeof InvestorUnitUnitIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/certifier'
    | '/developer'
    | '/investor'
    | '/login'
    | '/notary'
    | '/project'
    | '/certifier/assigned'
    | '/certifier/issued'
    | '/certifier/profile'
    | '/developer/audit-log'
    | '/developer/capital'
    | '/developer/documentation'
    | '/developer/investors'
    | '/developer/profile'
    | '/developer/progress'
    | '/developer/projects'
    | '/developer/units'
    | '/investor/buy'
    | '/investor/favorites'
    | '/investor/menu'
    | '/investor/notifications'
    | '/investor/profile'
    | '/investor/units'
    | '/notary/dossiers'
    | '/notary/profile'
    | '/notary/signed'
    | '/admin/'
    | '/certifier/'
    | '/developer/'
    | '/notary/'
    | '/certifier/stage/$stageId'
    | '/developer/project/new'
    | '/notary/dossier/$dossierId'
    | '/project/$projectId/developer'
    | '/project/$projectId/progress'
    | '/public/dossier/$shareToken'
    | '/project/$projectId/'
    | '/developer/project/$projectId/contracts'
    | '/developer/project/$projectId/invite'
    | '/developer/project/$projectId/units'
    | '/developer/project/$projectId/upload'
    | '/investor/unit/$unitId/contract'
    | '/investor/unit/$unitId/dossier'
    | '/investor/unit/$unitId/notifications'
    | '/project/$projectId/stage/$stageId'
    | '/developer/project/$projectId/'
    | '/investor/unit/$unitId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/investor'
    | '/login'
    | '/project'
    | '/certifier/assigned'
    | '/certifier/issued'
    | '/certifier/profile'
    | '/developer/audit-log'
    | '/developer/capital'
    | '/developer/documentation'
    | '/developer/investors'
    | '/developer/profile'
    | '/developer/progress'
    | '/developer/projects'
    | '/developer/units'
    | '/investor/buy'
    | '/investor/favorites'
    | '/investor/menu'
    | '/investor/notifications'
    | '/investor/profile'
    | '/investor/units'
    | '/notary/dossiers'
    | '/notary/profile'
    | '/notary/signed'
    | '/admin'
    | '/certifier'
    | '/developer'
    | '/notary'
    | '/certifier/stage/$stageId'
    | '/developer/project/new'
    | '/notary/dossier/$dossierId'
    | '/project/$projectId/developer'
    | '/project/$projectId/progress'
    | '/public/dossier/$shareToken'
    | '/project/$projectId'
    | '/developer/project/$projectId/contracts'
    | '/developer/project/$projectId/invite'
    | '/developer/project/$projectId/units'
    | '/developer/project/$projectId/upload'
    | '/investor/unit/$unitId/contract'
    | '/investor/unit/$unitId/dossier'
    | '/investor/unit/$unitId/notifications'
    | '/project/$projectId/stage/$stageId'
    | '/developer/project/$projectId'
    | '/investor/unit/$unitId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/certifier'
    | '/developer'
    | '/investor'
    | '/login'
    | '/notary'
    | '/project'
    | '/certifier/assigned'
    | '/certifier/issued'
    | '/certifier/profile'
    | '/developer/audit-log'
    | '/developer/capital'
    | '/developer/documentation'
    | '/developer/investors'
    | '/developer/profile'
    | '/developer/progress'
    | '/developer/projects'
    | '/developer/units'
    | '/investor/buy'
    | '/investor/favorites'
    | '/investor/menu'
    | '/investor/notifications'
    | '/investor/profile'
    | '/investor/units'
    | '/notary/dossiers'
    | '/notary/profile'
    | '/notary/signed'
    | '/admin/'
    | '/certifier/'
    | '/developer/'
    | '/notary/'
    | '/certifier/stage/$stageId'
    | '/developer/project/new'
    | '/notary/dossier/$dossierId'
    | '/project/$projectId/developer'
    | '/project/$projectId/progress'
    | '/public/dossier/$shareToken'
    | '/project/$projectId/'
    | '/developer/project/$projectId/contracts'
    | '/developer/project/$projectId/invite'
    | '/developer/project/$projectId/units'
    | '/developer/project/$projectId/upload'
    | '/investor/unit/$unitId/contract'
    | '/investor/unit/$unitId/dossier'
    | '/investor/unit/$unitId/notifications'
    | '/project/$projectId/stage/$stageId'
    | '/developer/project/$projectId/'
    | '/investor/unit/$unitId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CertifierRoute: typeof CertifierRouteWithChildren
  DeveloperRoute: typeof DeveloperRouteWithChildren
  InvestorRoute: typeof InvestorRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotaryRoute: typeof NotaryRouteWithChildren
  ProjectRoute: typeof ProjectRouteWithChildren
  PublicDossierShareTokenRoute: typeof PublicDossierShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/project': {
      id: '/project'
      path: '/project'
      fullPath: '/project'
      preLoaderRoute: typeof ProjectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notary': {
      id: '/notary'
      path: '/notary'
      fullPath: '/notary'
      preLoaderRoute: typeof NotaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investor': {
      id: '/investor'
      path: '/investor'
      fullPath: '/investor'
      preLoaderRoute: typeof InvestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer': {
      id: '/developer'
      path: '/developer'
      fullPath: '/developer'
      preLoaderRoute: typeof DeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certifier': {
      id: '/certifier'
      path: '/certifier'
      fullPath: '/certifier'
      preLoaderRoute: typeof CertifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notary/': {
      id: '/notary/'
      path: '/'
      fullPath: '/notary/'
      preLoaderRoute: typeof NotaryIndexRouteImport
      parentRoute: typeof NotaryRoute
    }
    '/developer/': {
      id: '/developer/'
      path: '/'
      fullPath: '/developer/'
      preLoaderRoute: typeof DeveloperIndexRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/certifier/': {
      id: '/certifier/'
      path: '/'
      fullPath: '/certifier/'
      preLoaderRoute: typeof CertifierIndexRouteImport
      parentRoute: typeof CertifierRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/notary/signed': {
      id: '/notary/signed'
      path: '/signed'
      fullPath: '/notary/signed'
      preLoaderRoute: typeof NotarySignedRouteImport
      parentRoute: typeof NotaryRoute
    }
    '/notary/profile': {
      id: '/notary/profile'
      path: '/profile'
      fullPath: '/notary/profile'
      preLoaderRoute: typeof NotaryProfileRouteImport
      parentRoute: typeof NotaryRoute
    }
    '/notary/dossiers': {
      id: '/notary/dossiers'
      path: '/dossiers'
      fullPath: '/notary/dossiers'
      preLoaderRoute: typeof NotaryDossiersRouteImport
      parentRoute: typeof NotaryRoute
    }
    '/investor/units': {
      id: '/investor/units'
      path: '/units'
      fullPath: '/investor/units'
      preLoaderRoute: typeof InvestorUnitsRouteImport
      parentRoute: typeof InvestorRoute
    }
    '/investor/profile': {
      id: '/investor/profile'
      path: '/profile'
      fullPath: '/investor/profile'
      preLoaderRoute: typeof InvestorProfileRouteImport
      parentRoute: typeof InvestorRoute
    }
    '/investor/notifications': {
      id: '/investor/notifications'
      path: '/notifications'
      fullPath: '/investor/notifications'
      preLoaderRoute: typeof InvestorNotificationsRouteImport
      parentRoute: typeof InvestorRoute
    }
    '/investor/menu': {
      id: '/investor/menu'
      path: '/menu'
      fullPath: '/investor/menu'
      preLoaderRoute: typeof InvestorMenuRouteImport
      parentRoute: typeof InvestorRoute
    }
    '/investor/favorites': {
      id: '/investor/favorites'
      path: '/favorites'
      fullPath: '/investor/favorites'
      preLoaderRoute: typeof InvestorFavoritesRouteImport
      parentRoute: typeof InvestorRoute
    }
    '/investor/buy': {
      id: '/investor/buy'
      path: '/buy'
      fullPath: '/investor/buy'
      preLoaderRoute: typeof InvestorBuyRouteImport
      parentRoute: typeof InvestorRoute
    }
    '/developer/units': {
      id: '/developer/units'
      path: '/units'
      fullPath: '/developer/units'
      preLoaderRoute: typeof DeveloperUnitsRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/projects': {
      id: '/developer/projects'
      path: '/projects'
      fullPath: '/developer/projects'
      preLoaderRoute: typeof DeveloperProjectsRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/progress': {
      id: '/developer/progress'
      path: '/progress'
      fullPath: '/developer/progress'
      preLoaderRoute: typeof DeveloperProgressRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/profile': {
      id: '/developer/profile'
      path: '/profile'
      fullPath: '/developer/profile'
      preLoaderRoute: typeof DeveloperProfileRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/investors': {
      id: '/developer/investors'
      path: '/investors'
      fullPath: '/developer/investors'
      preLoaderRoute: typeof DeveloperInvestorsRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/documentation': {
      id: '/developer/documentation'
      path: '/documentation'
      fullPath: '/developer/documentation'
      preLoaderRoute: typeof DeveloperDocumentationRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/capital': {
      id: '/developer/capital'
      path: '/capital'
      fullPath: '/developer/capital'
      preLoaderRoute: typeof DeveloperCapitalRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/audit-log': {
      id: '/developer/audit-log'
      path: '/audit-log'
      fullPath: '/developer/audit-log'
      preLoaderRoute: typeof DeveloperAuditLogRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/certifier/profile': {
      id: '/certifier/profile'
      path: '/profile'
      fullPath: '/certifier/profile'
      preLoaderRoute: typeof CertifierProfileRouteImport
      parentRoute: typeof CertifierRoute
    }
    '/certifier/issued': {
      id: '/certifier/issued'
      path: '/issued'
      fullPath: '/certifier/issued'
      preLoaderRoute: typeof CertifierIssuedRouteImport
      parentRoute: typeof CertifierRoute
    }
    '/certifier/assigned': {
      id: '/certifier/assigned'
      path: '/assigned'
      fullPath: '/certifier/assigned'
      preLoaderRoute: typeof CertifierAssignedRouteImport
      parentRoute: typeof CertifierRoute
    }
    '/project/$projectId/': {
      id: '/project/$projectId/'
      path: '/$projectId'
      fullPath: '/project/$projectId/'
      preLoaderRoute: typeof ProjectProjectIdIndexRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/public/dossier/$shareToken': {
      id: '/public/dossier/$shareToken'
      path: '/public/dossier/$shareToken'
      fullPath: '/public/dossier/$shareToken'
      preLoaderRoute: typeof PublicDossierShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project/$projectId/progress': {
      id: '/project/$projectId/progress'
      path: '/$projectId/progress'
      fullPath: '/project/$projectId/progress'
      preLoaderRoute: typeof ProjectProjectIdProgressRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/project/$projectId/developer': {
      id: '/project/$projectId/developer'
      path: '/$projectId/developer'
      fullPath: '/project/$projectId/developer'
      preLoaderRoute: typeof ProjectProjectIdDeveloperRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/notary/dossier/$dossierId': {
      id: '/notary/dossier/$dossierId'
      path: '/dossier/$dossierId'
      fullPath: '/notary/dossier/$dossierId'
      preLoaderRoute: typeof NotaryDossierDossierIdRouteImport
      parentRoute: typeof NotaryRoute
    }
    '/developer/project/new': {
      id: '/developer/project/new'
      path: '/project/new'
      fullPath: '/developer/project/new'
      preLoaderRoute: typeof DeveloperProjectNewRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/certifier/stage/$stageId': {
      id: '/certifier/stage/$stageId'
      path: '/stage/$stageId'
      fullPath: '/certifier/stage/$stageId'
      preLoaderRoute: typeof CertifierStageStageIdRouteImport
      parentRoute: typeof CertifierRoute
    }
    '/investor/unit/$unitId/': {
      id: '/investor/unit/$unitId/'
      path: '/unit/$unitId'
      fullPath: '/investor/unit/$unitId/'
      preLoaderRoute: typeof InvestorUnitUnitIdIndexRouteImport
      parentRoute: typeof InvestorRoute
    }
    '/developer/project/$projectId/': {
      id: '/developer/project/$projectId/'
      path: '/project/$projectId'
      fullPath: '/developer/project/$projectId/'
      preLoaderRoute: typeof DeveloperProjectProjectIdIndexRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/project/$projectId/stage/$stageId': {
      id: '/project/$projectId/stage/$stageId'
      path: '/$projectId/stage/$stageId'
      fullPath: '/project/$projectId/stage/$stageId'
      preLoaderRoute: typeof ProjectProjectIdStageStageIdRouteImport
      parentRoute: typeof ProjectRoute
    }
    '/investor/unit/$unitId/notifications': {
      id: '/investor/unit/$unitId/notifications'
      path: '/unit/$unitId/notifications'
      fullPath: '/investor/unit/$unitId/notifications'
      preLoaderRoute: typeof InvestorUnitUnitIdNotificationsRouteImport
      parentRoute: typeof InvestorRoute
    }
    '/investor/unit/$unitId/dossier': {
      id: '/investor/unit/$unitId/dossier'
      path: '/unit/$unitId/dossier'
      fullPath: '/investor/unit/$unitId/dossier'
      preLoaderRoute: typeof InvestorUnitUnitIdDossierRouteImport
      parentRoute: typeof InvestorRoute
    }
    '/investor/unit/$unitId/contract': {
      id: '/investor/unit/$unitId/contract'
      path: '/unit/$unitId/contract'
      fullPath: '/investor/unit/$unitId/contract'
      preLoaderRoute: typeof InvestorUnitUnitIdContractRouteImport
      parentRoute: typeof InvestorRoute
    }
    '/developer/project/$projectId/upload': {
      id: '/developer/project/$projectId/upload'
      path: '/project/$projectId/upload'
      fullPath: '/developer/project/$projectId/upload'
      preLoaderRoute: typeof DeveloperProjectProjectIdUploadRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/project/$projectId/units': {
      id: '/developer/project/$projectId/units'
      path: '/project/$projectId/units'
      fullPath: '/developer/project/$projectId/units'
      preLoaderRoute: typeof DeveloperProjectProjectIdUnitsRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/project/$projectId/invite': {
      id: '/developer/project/$projectId/invite'
      path: '/project/$projectId/invite'
      fullPath: '/developer/project/$projectId/invite'
      preLoaderRoute: typeof DeveloperProjectProjectIdInviteRouteImport
      parentRoute: typeof DeveloperRoute
    }
    '/developer/project/$projectId/contracts': {
      id: '/developer/project/$projectId/contracts'
      path: '/project/$projectId/contracts'
      fullPath: '/developer/project/$projectId/contracts'
      preLoaderRoute: typeof DeveloperProjectProjectIdContractsRouteImport
      parentRoute: typeof DeveloperRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CertifierRouteChildren {
  CertifierAssignedRoute: typeof CertifierAssignedRoute
  CertifierIssuedRoute: typeof CertifierIssuedRoute
  CertifierProfileRoute: typeof CertifierProfileRoute
  CertifierIndexRoute: typeof CertifierIndexRoute
  CertifierStageStageIdRoute: typeof CertifierStageStageIdRoute
}

const CertifierRouteChildren: CertifierRouteChildren = {
  CertifierAssignedRoute: CertifierAssignedRoute,
  CertifierIssuedRoute: CertifierIssuedRoute,
  CertifierProfileRoute: CertifierProfileRoute,
  CertifierIndexRoute: CertifierIndexRoute,
  CertifierStageStageIdRoute: CertifierStageStageIdRoute,
}

const CertifierRouteWithChildren = CertifierRoute._addFileChildren(
  CertifierRouteChildren,
)

interface DeveloperRouteChildren {
  DeveloperAuditLogRoute: typeof DeveloperAuditLogRoute
  DeveloperCapitalRoute: typeof DeveloperCapitalRoute
  DeveloperDocumentationRoute: typeof DeveloperDocumentationRoute
  DeveloperInvestorsRoute: typeof DeveloperInvestorsRoute
  DeveloperProfileRoute: typeof DeveloperProfileRoute
  DeveloperProgressRoute: typeof DeveloperProgressRoute
  DeveloperProjectsRoute: typeof DeveloperProjectsRoute
  DeveloperUnitsRoute: typeof DeveloperUnitsRoute
  DeveloperIndexRoute: typeof DeveloperIndexRoute
  DeveloperProjectNewRoute: typeof DeveloperProjectNewRoute
  DeveloperProjectProjectIdContractsRoute: typeof DeveloperProjectProjectIdContractsRoute
  DeveloperProjectProjectIdInviteRoute: typeof DeveloperProjectProjectIdInviteRoute
  DeveloperProjectProjectIdUnitsRoute: typeof DeveloperProjectProjectIdUnitsRoute
  DeveloperProjectProjectIdUploadRoute: typeof DeveloperProjectProjectIdUploadRoute
  DeveloperProjectProjectIdIndexRoute: typeof DeveloperProjectProjectIdIndexRoute
}

const DeveloperRouteChildren: DeveloperRouteChildren = {
  DeveloperAuditLogRoute: DeveloperAuditLogRoute,
  DeveloperCapitalRoute: DeveloperCapitalRoute,
  DeveloperDocumentationRoute: DeveloperDocumentationRoute,
  DeveloperInvestorsRoute: DeveloperInvestorsRoute,
  DeveloperProfileRoute: DeveloperProfileRoute,
  DeveloperProgressRoute: DeveloperProgressRoute,
  DeveloperProjectsRoute: DeveloperProjectsRoute,
  DeveloperUnitsRoute: DeveloperUnitsRoute,
  DeveloperIndexRoute: DeveloperIndexRoute,
  DeveloperProjectNewRoute: DeveloperProjectNewRoute,
  DeveloperProjectProjectIdContractsRoute:
    DeveloperProjectProjectIdContractsRoute,
  DeveloperProjectProjectIdInviteRoute: DeveloperProjectProjectIdInviteRoute,
  DeveloperProjectProjectIdUnitsRoute: DeveloperProjectProjectIdUnitsRoute,
  DeveloperProjectProjectIdUploadRoute: DeveloperProjectProjectIdUploadRoute,
  DeveloperProjectProjectIdIndexRoute: DeveloperProjectProjectIdIndexRoute,
}

const DeveloperRouteWithChildren = DeveloperRoute._addFileChildren(
  DeveloperRouteChildren,
)

interface InvestorRouteChildren {
  InvestorBuyRoute: typeof InvestorBuyRoute
  InvestorFavoritesRoute: typeof InvestorFavoritesRoute
  InvestorMenuRoute: typeof InvestorMenuRoute
  InvestorNotificationsRoute: typeof InvestorNotificationsRoute
  InvestorProfileRoute: typeof InvestorProfileRoute
  InvestorUnitsRoute: typeof InvestorUnitsRoute
  InvestorUnitUnitIdContractRoute: typeof InvestorUnitUnitIdContractRoute
  InvestorUnitUnitIdDossierRoute: typeof InvestorUnitUnitIdDossierRoute
  InvestorUnitUnitIdNotificationsRoute: typeof InvestorUnitUnitIdNotificationsRoute
  InvestorUnitUnitIdIndexRoute: typeof InvestorUnitUnitIdIndexRoute
}

const InvestorRouteChildren: InvestorRouteChildren = {
  InvestorBuyRoute: InvestorBuyRoute,
  InvestorFavoritesRoute: InvestorFavoritesRoute,
  InvestorMenuRoute: InvestorMenuRoute,
  InvestorNotificationsRoute: InvestorNotificationsRoute,
  InvestorProfileRoute: InvestorProfileRoute,
  InvestorUnitsRoute: InvestorUnitsRoute,
  InvestorUnitUnitIdContractRoute: InvestorUnitUnitIdContractRoute,
  InvestorUnitUnitIdDossierRoute: InvestorUnitUnitIdDossierRoute,
  InvestorUnitUnitIdNotificationsRoute: InvestorUnitUnitIdNotificationsRoute,
  InvestorUnitUnitIdIndexRoute: InvestorUnitUnitIdIndexRoute,
}

const InvestorRouteWithChildren = InvestorRoute._addFileChildren(
  InvestorRouteChildren,
)

interface NotaryRouteChildren {
  NotaryDossiersRoute: typeof NotaryDossiersRoute
  NotaryProfileRoute: typeof NotaryProfileRoute
  NotarySignedRoute: typeof NotarySignedRoute
  NotaryIndexRoute: typeof NotaryIndexRoute
  NotaryDossierDossierIdRoute: typeof NotaryDossierDossierIdRoute
}

const NotaryRouteChildren: NotaryRouteChildren = {
  NotaryDossiersRoute: NotaryDossiersRoute,
  NotaryProfileRoute: NotaryProfileRoute,
  NotarySignedRoute: NotarySignedRoute,
  NotaryIndexRoute: NotaryIndexRoute,
  NotaryDossierDossierIdRoute: NotaryDossierDossierIdRoute,
}

const NotaryRouteWithChildren =
  NotaryRoute._addFileChildren(NotaryRouteChildren)

interface ProjectRouteChildren {
  ProjectProjectIdDeveloperRoute: typeof ProjectProjectIdDeveloperRoute
  ProjectProjectIdProgressRoute: typeof ProjectProjectIdProgressRoute
  ProjectProjectIdIndexRoute: typeof ProjectProjectIdIndexRoute
  ProjectProjectIdStageStageIdRoute: typeof ProjectProjectIdStageStageIdRoute
}

const ProjectRouteChildren: ProjectRouteChildren = {
  ProjectProjectIdDeveloperRoute: ProjectProjectIdDeveloperRoute,
  ProjectProjectIdProgressRoute: ProjectProjectIdProgressRoute,
  ProjectProjectIdIndexRoute: ProjectProjectIdIndexRoute,
  ProjectProjectIdStageStageIdRoute: ProjectProjectIdStageStageIdRoute,
}

const ProjectRouteWithChildren =
  ProjectRoute._addFileChildren(ProjectRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CertifierRoute: CertifierRouteWithChildren,
  DeveloperRoute: DeveloperRouteWithChildren,
  InvestorRoute: InvestorRouteWithChildren,
  LoginRoute: LoginRoute,
  NotaryRoute: NotaryRouteWithChildren,
  ProjectRoute: ProjectRouteWithChildren,
  PublicDossierShareTokenRoute: PublicDossierShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
