export { auditoriaQueries } from './auditoria'
export { capitalQueries } from './capital'
export { certificadoQueries } from './certificado'
export { contratoQueries } from './contrato'
export { dossierQueries } from './dossier'
export { etapaQueries } from './etapa'
export { archivoQueries, evidenciaQueries } from './evidencia'
export { favoritoQueries } from './favorito'
export { invalidaciones, invalidar } from './invalidaciones'
export { invitacionQueries } from './invitacion'
export { kpiQueries } from './kpi'
export { notificacionQueries } from './notificacion'
export { proyectoQueries } from './proyecto'
export { unidadQueries } from './unidad'
export { usuarioQueries } from './usuario'
